# Generated by Django 6.0.1 on 2026-02-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_method', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('phone', 'Телефон'), ('email', 'Email'), ('other', 'Другое')], max_length=20)),
                ('contact', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_conducted', models.BooleanField(default=False)),
            ],
        ),
    ]
