# Generated by Django 6.0.1 on 2026-02-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_consult', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationrequest',
            old_name='comment',
            new_name='message',
        ),
    ]
