# Generated by Django 6.0.1 on 2026-02-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_consult', '0002_rename_comment_consultationrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='contact',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
